### PR TITLE
fix(website): different email addresses

### LINKED ISSUE #141: Unify email links
Currently, the links in different places point to different email addresses.
They should all lead to a single one (ask Dima which one to use):

1. In the website footer
2. On the Policy page

Image

### PR DESCRIPTION
**Pull request by alsakhaev**

### CODE REVIEW

File: website/src/components/Footer/index.tsx [hunk 1]
```diff
@@ -100,7 +100,7 @@ export function Footer() {
         <Link
           prefetch={false}
           target='_blank'
-          href='mailto:business@dapplets.org'
+          href='mailto:contact@dapplets.org'
```
Comment (Ni-2) [inline website/src/components/Footer/index.tsx:103]: Done 👍
