### PR TITLE
fix: add hover state to a capability with an action (issue#196)

### LINKED ISSUE #196: No Hover State
The arrow next to News Monitor has no hover state (no pointer cursor and color change on hover)

### PR DESCRIPTION
**Pull request by Ni-2**
#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Bug fix
[ ] New feature
[ ] Documentation update
[ ] Add something to the core
[ ] Other, please explain:

#### Add a reference to a related issue if it exists

*issue:*

### CODE REVIEW

File: apps/xen-tg-app/src/components/Agent.tsx [hunk 1]
```diff
@@ -73,10 +73,17 @@ const Agent: FC<TAgentProps> = ({ capabilitiy }) => {
   // })
   return (
     <div className="flex w-full items-center justify-between gap-3.5 rounded-[10px] bg-(--color-light-white-bg) p-2.5">
-      <button className="flex flex-1 flex-col gap-0.5 overflow-hidden" onClick={action}>
-        <div className="flex items-center gap-2 py-0.25 text-left text-[14px]/[100%] font-semibold wrap-anywhere">
+      <button
+        className={`flex flex-1 ${action ? 'cursor-pointer' : 'cursor-default'} flex-col gap-0.5 overflow-hidden`}
+        onClick={action}
```
Comment (alsakhaev) [inline apps/xen-tg-app/src/components/Agent.tsx:78]: confusing name of the handler

**Review by alsakhaev — CHANGES_REQUESTED** [review]
