### PR TITLE
feat: change capability buttons to switches fixed (issue #167)

### LINKED ISSUE #167: Change capability buttons to switches
Image

### PR DESCRIPTION
**Pull request by Ni-2**
#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Bug fix
[x] New feature
[ ] Documentation update
[ ] Add something to the core
[ ] Other, please explain:

#### Add a reference to a related issue if it exists

*issue:*

### CODE REVIEW

File: apps/xen-tg-app/src/components/Agent.tsx [hunk 1]
```diff
@@ -65,9 +65,9 @@ const Agent: FC<TAgentProps> = ({ capabilitiy }) => {
           {capabilitiy.domain}
         </div>
       </div>
-      <button
-        className={`flex h-9 w-15 shrink-0 cursor-pointer items-center justify-center rounded-[10px] text-xs/[100%] font-normal dark:bg-(--color-light-white-bg) ${capabilitiy.isEnabled ? 'bg-(--color-my-primary) text-(--color-opposite-text) dark:text-(--color-my-primary)' : 'bg-(--color-opposite-text) text-(--color-gray-text) dark:text-(--color-gray-text)'} capitalize`}
-        onClick={() =>
+
+      <Switch
+        onCheckedChange={() =>
```
Comment (alsakhaev) [inline apps/xen-tg-app/src/components/Agent.tsx:70]: extract to separate handler function please
keep jsx code clean

**Review by alsakhaev — CHANGES_REQUESTED** [review]

File: apps/xen-tg-app/src/components/Agent.tsx (hunk 1 above)
Comment (alsakhaev) [inline apps/xen-tg-app/src/components/Agent.tsx]: extract to separate handler function please
keep jsx code clean

**Review by alsakhaev — CHANGES_REQUESTED** [review]
