### PR TITLE
fix(website): different links to the Chrome Web Store

### LINKED ISSUE #140: fix(website): different links to the Chrome Web Store
Currently, the links in different places lead to different extensions.
All three links should point to the Mutable Web extension:

1. 'Get Started' on the HOME page
2. 'Get Started' on the ABOUT page
3. Here

Image

### PR DESCRIPTION
**Pull request by alsakhaev**

### CODE REVIEW

File: website/src/components/HomePage/FeaturesSection.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ const FeatureLink = () => {
       ref={linkRef}
       prefetch={false}
       target='_blank'
-      href='https://chrome.google.com/webstore/detail/dapplets/pjjnaojpjhgbhpfffnjleidmdbajagdj'
+      href='https://chromewebstore.google.com/detail/mutable-web/cnahdmdbhkphpbpbjjbfdnmbphbenglc'
```
Comment (Ni-2) [inline website/src/components/HomePage/FeaturesSection.tsx:42]: Why did you change `chrome.google.com` to `chromewebstore.google.com`?

Comment (alsakhaev) [reply website/src/components/HomePage/FeaturesSection.tsx:42]: looks that `chrome.google.com` is outdated, because they redirect to `chromewebstore.google.com`
