### PR TITLE
fix: show all subscriptions and Memories in Xen Telegram app (issue#280)

### LINKED ISSUE #280: Show all subscriptions and Memories in Xen Telegram app
If it's not require more than 2 hours, add pagination. If it is so, increase a limit to 100 items.

### PR DESCRIPTION
**Pull request by Ni-2**
#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Bug fix
[ ] New feature
[ ] Documentation update
[ ] Add something to the core
[ ] Other, please explain:

#### Add a reference to a related issue if it exists

*issue:*

### CODE REVIEW

File: apps/xen-tg-app/src/components/NewsMonitor.tsx [hunk 1]
```diff
@@ -67,22 +84,61 @@ const queryFn = (name: string, params?: { [key: string]: string | number }) => a
 const NewsMonitor = () => {
```
Comment (alsakhaev) [inline apps/xen-tg-app/src/components/NewsMonitor.tsx:84]: In the future, it's better to move all the logic for infinite scrolling into a separate component and reuse it in all cases. The pagination API in the backend is the same there.
